### PR TITLE
feat(sound): Aether II Portal sounds

### PR DESCRIPTION
**Pull request by Zepalesque**
The swirly-sounding Aether Portal sounds, from the Aether II
At some point (I may even do this sometime) it may be a smart idea to add a system to prevent overlap of these sounds

Note: this uses semi-hacky mixin implementation, hopefully that won't be a huge issue

closes issue #63 

---

I agree to the Contributor License Agreement (CLA).

### CODE REVIEW

**Review by bconlon1 — CHANGES_REQUESTED** [review]
Wouldn't you be able to use Forge's `PlaySoundEvent` for this?

**Comment by Zepalesque** [comment]
for some odd reason, using that crashes if you try to invoke some methods from `getOriginalSound()` as it is apparently null (oddly, `getSource()` works but not `getVolume()`)
I actually had a similar issue to this a while ago, I had forgotten why it didn't work until now though
however that reminds me of `PlayLevelSoundEvent` which could potentially work instead

**Comment by bconlon1** [comment]
Try `getSound()` or null checks.

**Comment by Zepalesque** [comment]
unfortunately it still has the same issue
I also tried using `PlayLevelSoundEvent`, but since the portal sounds are client-side, that did not work either

**Review by bconlon1 — APPROVED** [review]
lgtm

**Review by bconlon1 — CHANGES_REQUESTED** [review]
Nevermind the latest changes to Genesis have to be merged into this because of the Aether codebase cleanup breaking things

**Comment by Zepalesque** [comment]
alright, fixed those issues

**Review by bconlon1 — APPROVED** [review]
lgtm

**Pull request merged**
